mongodb_downloadurl: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel70-4.2.8.tgz
mongodb_admin_user: "{{ uberspace_loginname }}_mongoroot"
mongodb_admin_password: "{{ lookup('password', 'credentials/' + 'mongodb_admin_password') }}"
