- name: Reread supervisord config for postgresql
  command:
    cmd: supervisorctl reread
  notify: Update supervisord group postgresql
- name: Update supervisord group postgresql
  command:
    cmd: supervisorctl update postgresql
  notify: Restart postgresql
- name: Restart postgresql
  command:
    cmd: supervisorctl restart postgresql
