namespace: "friesenkiwi"
name: "uberspace"
version: "2.0.0"
readme: "README.md"
authors:
- "Friesenkiwi"
tags:
- uberspace
- webhosting
- hosting
repository: "https://github.com/friesenkiwi/ansible-collection-uberspace"
