wekan_version: 6.41
wekan_port:
wekan_secret: "{{ lookup('password', 'credentials/' + 'wekan_secret') }}"
wekan_db_user: wekan
wekan_db_pw: "{{ lookup('password', 'credentials/' + 'wekan_mongodb_user_pw') }}"
wekan_db_name: wekan
wekan_db_host: "{{ uberspace_spacedir }}/tmp/"
mongodb_application_user: "{{ wekan_db_user }}"
mongodb_application_password: "{{ wekan_db_pw }}"
