wekan_secret: "{{ lookup('password', 'credentials/' + 'wekan_secret') }}"
wekan_db_user: wekan
wekan_db_pw: "{{ lookup('password', 'credentials/' + 'wekan_postgresql_user_pw') }}"
wekan_db_name: wekan_dev
wekan_db_host: "{{ uberspace_spacedir }}/tmp/"
wekan_mongo_user: "{{ uberspace_loginname }}_mongoadmin"
