- name: Reread supervisord config
  command:
    cmd: supervisorctl reread
  notify: Update supervisord group pleroma
- name: Update supervisord group pleroma
  command:
    cmd: supervisorctl update pleroma
  notify: Restart pleroma
- name: Restart pleroma
  command:
    cmd: supervisorctl restart pleroma
