- name: Reread supervisord config
  command:
    cmd: supervisorctl reread
  notify: Update supervisord group coturn
- name: Update supervisord group coturn
  command:
    cmd: supervisorctl update coturn
  notify: Restart coturn
- name: Restart coturn
  command:
    cmd: supervisorctl restart coturn
