- name: Reread supervisord config
  command:
    cmd: supervisorctl reread
  notify: Update supervisord group uwsgi
- name: Update supervisord group uwsgi
  command:
    cmd: supervisorctl update uwsgi
  notify: Restart uwsgi
- name: Restart uwsgi
  command:
    cmd: supervisorctl restart uwsgi
