- name: Get accounting page for CSRF token
  check_mode: no
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.accounting }}"
    headers: "{{ uberspace_headers }}"
    return_content: yes
    follow_redirects: none
  register: formresult

# - name: Show current price
#   debug:
#     msg: "{{ uberspace_price_current }}"
#
# - name: Show uberspace_price_goal
#   debug:
#     msg: "{{ uberspace_price_goal }}"
#
# - name: Show uberspace_price_crossfinanced_limit
#   debug:
#     msg: "{{ uberspace_price_crossfinanced_limit }}"
#
# - name: Show uberspace_price_crossfinanced_check
#   debug:
#     msg: "{{ uberspace_price_crossfinanced_check }}"

- name: Set price if different
  delegate_to: localhost
  when: (uberspace_price_goal | float != uberspace_price_current | float) and uberspace_price_crossfinanced_check
  uri:
    url: "{{ uberspace_urls.setprice }}"
    headers: "{{ uberspace_headers }}"
    method: POST
    return_content: yes
    body_format: form-urlencoded
    body:
      _csrf_token: "{{ csrftoken }}"
      price: "{{ uberspace_price_goal }}"
      came_from_cross_financed_price: "{{ (uberspace_price_goal < uberspace_price_crossfinanced_limit) | ternary('1', omit) }}"
    status_code: 302
    follow_redirects: all
  changed_when: true
  failed_when: not uberspace_price_crossfinanced_check
  register: accountingresult

# - name: Show accountingresult
#   debug:
#     msg: "{{ accountingresult }}"

- name: Set new current price as fact
  when: accountingresult is defined and (accountingresult.skipped is not defined or (accountingresult.skipped is defined and accountingresult.skipped != true))
  set_fact:
    uberspace_price_current: "{{ parsed_currentprice }}"

# - name: Show current price
#   debug:
#     msg: "{{ uberspace_price_current }}"

- name: Record current price as custom stat (set show_custom_stats = yes in ansible.cfg or ANSIBLE_SHOW_CUSTOM_STATS=yes in env)
  set_stats:
    per_host: yes
    aggregate: false
    data:
      currentprice: "{{ uberspace_price_current }}"
