# Only works after DNS has been set up
- name: Touch web URL to trigger certificate generation
  tags:
  - domains
  - certificates
  loop: "{{ uberspace_domains_goal | default([]) }}"
  uri:
    url: "https://{{ item }}"
  register: certificates
  failed_when: certificates.status == -1
  changed_when: certificates.elapsed > 10
- name: Show certificates
  debug:
    msg: "{{ certificates }}"
