- name: Get deletion page for CSRF token
  tags: delete
  delegate_to: localhost
  check_mode: no
  uri:
    url: "{{ uberspace_urls.delete }}"
    headers: "{{ uberspace_headers }}"
    return_content: yes
  register: formresult

# - name: Show deletion page result
#   tags: delete
#   debug:
#     msg: "{{ formresult }}"

- name: Delete uberspace
  tags: delete
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.deletequeue }}"
    headers: "{{ uberspace_headers }}"
    method: POST
    body_format: form-urlencoded
    body:
      _csrf_token: "{{ csrftoken }}"
    status_code: 302
  register: deleteresult
  changed_when: (deleteresult.location == uberspace_urls.deleteresult_register) or (deleteresult.location == uberspace_urls.deleteresult_login)

- name: Show deletion result
  tags: delete
  debug:
    msg: "{{ deleteresult }}"
