# - name: Show uberspace_domains_goal
#   tags: domains
#   debug:
#     msg: "{{ uberspace_domains_goal }}"
# - name: Show uberspace_domains
#   tags: domains
#   debug:
#     msg: "{{ uberspace_domains }}"

- name: Add domains to uberspace config
  tags: domains
  loop: "{{ uberspace_domains_goal | default([]) }}"
  when: item not in uberspace_domains
  command: "uberspace web domain add {{ item }}"
  register: addeddomains

# - name: show addeddomains
#   tags: domains
#   debug:
#     msg: "{{ addeddomains }}"
# - name: Run certificates task
#   tags: domains
#   import_tasks: certificates.yml
