- name: Get datasheet page
  delegate_to: localhost
  check_mode: no
  uri:
    url: "{{ uberspace_urls.datasheet }}"
    headers: "{{ uberspace_headers }}"
    return_content: yes
  register: datasheetresult

- name: Set uberspace facts from dashboard
  set_fact:
    uberspace_ip_public_v4: "{{ parsed_ipv4address }}"
    uberspace_ip_public_v6: "{{ parsed_ipv6address }}"
    uberspace_hostname: "{{ parsed_hostname }}"

- name: Get accounting page
  delegate_to: localhost
  check_mode: no
  uri:
    url: "{{ uberspace_urls.accounting }}"
    headers: "{{ uberspace_headers }}"
    return_content: yes
  register: accountingresult

- name: Set uberspace facts from accounting
  set_fact:
    uberspace_balance: "{{ parsed_balance }}"
    uberspace_price_current: "{{ parsed_currentprice }}"

- name: Put host keys into local known_hosts
  delegate_to: localhost
  vars:
    hostkey: "{{ lookup('pipe','ssh-keyscan -t ' + item + ' ' + uberspace_domain_official + ' 2>/dev/null | cut -d \" \" -f 1 --complement') }}"
    actual_hostkey_fingerprint: "{{ lookup('pipe','echo \"' + hostkey + '\" | ssh-keygen -l -f - | cut -d \" \" -f 2 | cut -d \":\" -f 2') }}"
    ssh_hostnames:
    - "{{ uberspace_domain_official }}"
    - "{{ uberspace_ip_public_v4 }}"
    - "{{ uberspace_ip_public_v6 }}"
  loop:
  - ed25519
  - rsa
  when: actual_hostkey_fingerprint == parsed_hostkeyfingerprint
  known_hosts:
    name: "{{ uberspace_domain_official }}"
    key: "{{ ssh_hostnames | join(',') }} {{ hostkey }}"

- name: Gather facts
  tags: dev_gatherfacts
  gather_facts:

# TODO replace with using default collected facts from /etc/ansible/facts.d , /opt/uberspace/userfacts/foobar2/ into ansible_local.
# Only available if configured e.g. ports at refuger (prosody)
- name: Show all facts
  tags: dev_gatherfacts
  debug:
    msg: "{{ ansible_facts }}"
- name: Show some facts
  tags: dev_gatherfacts
  debug:
    msg: "{{ ansible_local }}"

- name: Set uberspace facts from ansible facts
  set_fact:
    uberspace_ip_private_v4: "{{ ansible_default_ipv4.address }}"
    uberspace_ip_private_v6: "{{ ansible_default_ipv6.address }}"
    uberspace_host: "{{ ansible_hostname }}"
    uberspace_domains: "{{ ((ansible_local.users[uberspace_loginname].domains) | default({})).keys() | list }}"
    uberspace_ports: "{{ ansible_local.users[uberspace_loginname].public_ports | default([]) }}"
    uberspace_webbackends: "{{ ansible_local.users[uberspace_loginname].global_backends | default([]) }}" # overwritten later
    uberspace_webheaders: "{{ ansible_local.users[uberspace_loginname].global_headers | default([]) }}"
    uberspace_tools_versions: "{{ ansible_local.users[uberspace_loginname].versions }}" # overwritten later

- name: Retrieve web backends
  tags: backends
  check_mode: no
  command: "uberspace web backend list"
  changed_when: false
  register: uberspace_webbackends
- name: Store web backends as fact
  tags: backends,dev_gatherfacts
  set_fact:
    uberspace_webbackends: "{{ uberspace_webbackends.stdout_lines | default([]) }}"

- name: Blow up web backends
  tags: backends,dev_gatherfacts
  loop: "{{ ansible_local.users[uberspace_loginname].domains | default({}) | dict2items }}"
  vars:
    backends_per_domain: "{{ [{'domain': item.key, 'backends': (item.value.web.backends | default({}) | dict2items) } ] }}"
    backends_per_domain_blownup: "{{ backends_per_domain | subelements('backends') }}"
  set_fact:
    all_backends_per_domain_blownup: "{{ all_backends_per_domain_blownup | default([]) + backends_per_domain_blownup }}"

- name: Show blown-up web backends
  tags: dev_gatherfacts
  debug:
    msg: "{{ all_backends_per_domain_blownup | default([]) }}"

- name: Structure web backends
  tags: backends,dev_gatherfacts
  loop: "{{ all_backends_per_domain_blownup | default([]) }}"
  vars:
    backend_structured: "{{ {'domain': item[0].domain, 'path': item[1].key, 'port': item[1].value.port, 'remove_prefix': item[1].value.remove_prefix, 'transport': item[1].value.transport} }}"
  set_fact:
    all_backends_structured: "{{ all_backends_structured | default([]) + [ backend_structured ] }}"

- name: Show global web backends
  tags: dev_gatherfacts
  debug:
    msg: "{{ ansible_local.users[uberspace_loginname].global_backends | default([]) }}"

- name: Show structured web backends
  tags: dev_gatherfacts
  debug:
    msg: "{{ all_backends_structured | default([]) }}"

- name: Retrieve tools list
  tags: tools
  check_mode: no
  command: "uberspace tools version list"
  changed_when: false
  register: uberspace_tools
- name: Store tools as fact
  tags: tools
  set_fact:
    uberspace_tools: "{{ uberspace_tools.stdout_lines | map('regex_replace', '- ', '') | list }}"

- name: Get MySQL my.cnf file
  tags: mysql
  check_mode: no
  fetch:
    flat: yes
    src: ".my.cnf"
    dest: "{{ uberspace_mycnffetch_destination }}"

- name: Store MySQL passwords as fact
  tags: mysql
  set_fact:
    uberspace_mysqlpassword: "{{ lookup('ini', 'password section=client file=' + uberspace_mycnffetch_destination) }}"
    uberspace_mysqlpassword_readonly: "{{ lookup('ini', 'password section=clientreadonly file=' + uberspace_mycnffetch_destination) }}"

- name: Record some facts as custom stat (set show_custom_stats = yes in ansible.cfg or ANSIBLE_SHOW_CUSTOM_STATS=yes in env)
  set_stats:
    per_host: yes
    data:
      balance: "{{ uberspace_balance }}"
      currentprice: "{{ uberspace_price_current }}"
