- name: Get login form for CSRF token
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.login }}"
    return_content: yes
  register: formresult

- name: Login to get session
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.login }}"
    method: POST
    body_format: form-urlencoded
    body:
      _csrf_token: "{{ csrftoken }}"
      login: "{{ uberspace_loginname }}"
      password: "{{ uberspace_loginpassword }}"
      submit: "login"
    status_code: 302
  register: loginresult

- name: Store session cookie as fact
  set_fact:
    uberspace_cookie: "{{ loginresult.set_cookie.split(';')[0] }}"

- name: Store session to a local file
  delegate_to: localhost
  copy:
    content: "{{ uberspace_cookie.split('=')[1] }}"
    dest: "{{ uberspace_sessionfile }}"
