- name: Check loginname availability
  tags: session
  delegate_to: localhost
  check_mode: no
  uri:
    url: "{{ uberspace_urls.register }}"
  register: checkresult
  failed_when: checkresult.status!=200 and checkresult.status!=403
# - name: Setup application
#   debug:
#     msg: "{{checkresult}}"
- name: Do registration
  when: uberspace_action_setup and checkresult.status==200 and checkresult.msg == "OK (16 bytes)"
  include_tasks: register.yml
- name: Lookup session
  tags: session
  vars:
    uberspace_session:  "{{ lookup('file', uberspace_sessionfile, errors='ignore') }}"
  when: uberspace_session | default('', true) | trim != ''
  set_fact:
    uberspace_cookie: "uberspace_session={{ uberspace_session }}"
- name:
  tags: session
  check_mode: no
  block:
  - name: Get main dashboard page to check if session expired
    delegate_to: localhost
    uri:
      url: "{{ uberspace_url_dashboard }}"
      headers: "{{ uberspace_headers }}"
      return_content: yes
      follow_redirects: none
    register: dashboardresult
  rescue:
  - name: Re-login
    include_tasks: login.yml
- name: Do login
  tags: session
  when: checkresult.status==403 and uberspace_cookie is not defined
  include_tasks: login.yml
- name: Do passwordset
  when: uberspace_action_setup
  include_tasks: password.yml
- name: Do key deployment
  when: uberspace_action_setup
  import_tasks: key.yml
- name: Do facts gathering
  tags: gatherfacts
  when: not uberspace_action_delete
  import_tasks: gather_facts.yml
- name: Do basic space setup
  tags: basics
  when: not uberspace_action_delete
  import_tasks: basics.yml
- name: Do space accounting
  tags: accounting
  when: not uberspace_action_delete
  import_tasks: accounting.yml
- name: Do domain setup
  tags: domains
  when: not uberspace_action_delete
  import_tasks: domains.yml
- name: Do port setup
  tags: ports
  when: not uberspace_action_delete
  import_tasks: ports.yml
- name: Do web backend setup
  tags: backends
  when: not uberspace_action_delete
  import_tasks: webbackends.yml
- name: Do web tools setup
  tags: tools
  when: not uberspace_action_delete
  import_tasks: tools.yml
- name: Do delete
  tags: delete
  when: uberspace_action_delete
  include_tasks: delete.yml
