- name: Get authentication page for CSRF token
  check_mode: false
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.authentication }}"
    headers: "{{ uberspace_headers }}"
    return_content: true
    follow_redirects: none
  register: formresult

- name: Set password
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.setwebpassword }}"
    headers: "{{ uberspace_headers }}"
    method: POST
    follow_redirects: none
    body_format: form-urlencoded
    body:
      _csrf_token: "{{ csrftoken }}"
      password: "{{ uberspace_newloginpassword }}"
    status_code: 302
