- name: Get register form for CSRF token
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.registerform }}"
    return_content: yes
  register: formresult

- name: Store session as cookie
  set_fact:
    uberspace_cookie: "{{ formresult.set_cookie.split(';')[0] }}"

- name: Register
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.create }}"
    method: POST
    headers: "{{ uberspace_headers }}"
    body_format: form-urlencoded
    body:
      _csrf_token: "{{ csrftoken }}"
      mailaddr: "{{ uberspace_registeradminnmailaddress }}"
      login: "{{ uberspace_loginname }}"
      houserules: 1
      password: "{{ uberspace_newloginpassword }}"
    return_content: yes
    status_code: 302
  register: registerresult
  # Forwards to https://dashboard.uberspace.de/register/../dashboard/while_u_wait

- name: Output registerresult
  debug:
    var: registerresult

- name: Store session cookie as fact
  set_fact:
    uberspace_cookie: "{{ registerresult.set_cookie.split(';')[0] }}"

- name: Output session cookie
  debug:
    msg: "{{ uberspace_cookie }}"

- name: Store session to a local file
  delegate_to: localhost
  copy:
    content: "{{ uberspace_cookie.split('=')[1] }}"
    dest: "{{ uberspace_sessionfile }}"

# TODO: In the future probably check https://dashboard.uberspace.de/register/../dashboard/while_u_wait (HTTP Refresh), will 302 forward to "{{ uberspace_urls.datasheet }}" as soon as creation is finished
- name: Wait for space creation to finish
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.check }}"
    follow_redirects: none
    method: GET
    return_content: yes
    headers: "{{ uberspace_headers }}"
  register: checkresult
  until: checkresult.content == "active"
  retries: 60
  delay: 5 # Every 5 seconds
# - name: Output checkresult
#   debug:
#     var: checkresult

- name: Get firstboot (datasheet) page
  delegate_to: localhost
#  ignore_errors: true
  uri:
    url: "{{ uberspace_urls.datasheet }}"
    method: GET
    return_content: yes
    headers: "{{ uberspace_headers }}"
  register: firstbootresult

# - name: Show firstboot (datasheet) page
#   debug:
#     var: firstbootresult
