- name: Filter list of tools goal
  tags: tools
  loop: "{{ uberspace_tools_goal | default({}) | dict2items }}"
  when: (item.key in uberspace_tools_goal_only | default([])) or ((uberspace_tools_goal_only | default([])) | length == 0)
  set_fact:
    uberspace_tools_goal_filtered: "{{ uberspace_tools_goal_filtered | default({}) | combine ([item] | items2dict) }}"

- name: Set tools versions
  tags: tools
  loop: "{{ uberspace_tools_goal_filtered | dict2items }}"
  when: uberspace_tools[item.key] != item.value
  command: "uberspace tools version use {{ item.key }} {{ item.value }}"
  register: toolsversionresult
  changed_when: toolsversionresult.rc == 0
#- name: Output tools versions configuration results
#  debug:
#    msg: "{{ toolsversionresult }}"

- name: Reset list of tools goal
  tags: tools
  set_fact:
    uberspace_tools_goal_filtered: {}
