# uberspace web header set /.well-known Access-Control-Allow-Origin "*"
# uberspace web header set /http-bind Access-Control-Allow-Origin "*"
# uberspace web header list
# /.well-known
#   Access-Control-Allow-Origin: *
# /http-bind
#   Access-Control-Allow-Origin: *
# Default Headers:
#   Referrer-Policy: strict-origin-when-cross-origin
#   Strict-Transport-Security: max-age=31536000
#   X-Content-Type-Options: nosniff
#   X-Frame-Options: SAMEORIGIN
#   X-Xss-Protection: 1; mode=block
