pleroma_project_name: "pleroma"
pleroma_main_dir: "{{ uberspace_projectsdir | realpath }}/{{ pleroma_project_name }}"

pleroma_port: 4000
pleroma_instancename: Pleroma
pleroma_adminmail: admin@example.com

pleroma_host: "{{ uberspace_servicedomain }}.{{ uberspace_basedomain }}"
pleroma_db_user: "{{ uberspace_loginname }}_{{ pleroma_project_name }}"
pleroma_db_pw: "{{ lookup('password', 'credentials/' + uberspace_loginname + '/' + 'pleroma_postgresql_user_pw') }}"
pleroma_db_name: "{{ pleroma_db_user }}"
pleroma_db_host: "{{ uberspace_spacedir }}/tmp/"

pleroma_mix_environment: prod
pleroma_environment:
  MIX_ENV: "{{ pleroma_mix_environment }}"
pleroma_environment_string: "{{ pleroma_environment.items()|map('join', '=')|join('') }}"
pleroma_config_genquestion_responses:
  'Shall I install rebar3': 'Y'
  'What domain will your instance use': "{{ pleroma_host }}"
  'What is the name of your instance': "{{ pleroma_instancename }}"
  'What is your admin email address': "{{ pleroma_adminmail }}"
  'What email address do you want to use for sending email notifications': "{{ pleroma_adminmail }}"
  'Do you want search engines to index your site': 'n'
  'Do you want to store the configuration in the database': 'n'
  'What is the hostname of your database': 'localhost'
  'What is the name of your database': "{{ pleroma_db_name }}"
  'What is the user used to connect to your database': "{{ pleroma_db_user }}"
  'What is the password used to connect to your database': "{{ pleroma_db_pw }}"
  'Would you like to use RUM indices': 'n'
  'What port will the app listen to': "{{ pleroma_port }}"
  'What ip will the app listen to': "{{ pleroma_interface_ipv4 }}"
  'What directory should media uploads go in': 'uploads'
  'What directory should custom public files be read from': 'instance/static/'
  'Do you want to strip location \(GPS\) data from uploaded images': 'y'
  'Do you want to read data from uploaded files so clients can use it to prefill fields like image description': 'n'
  'Do you want to anonymize the filenames of uploads': 'y'
  'Do you want to deduplicate uploaded files': 'y'
pleroma_config_adjustments:
- line: '  registrations_open: false'
  regexp: '^  registrations_open:'
  insertafter: "^config :pleroma, :instance,$"
- line: '  public: false,'
  regexp: '^  public:'
  insertafter: "^config :pleroma, :instance,$"
- line: '  remote_post_retention_days: 28,'
  regexp: '^  remote_post_retention_days:'
  insertafter: "^config :pleroma, :instance,$"
- line: '  queue_target: 5000,'
  regexp: '^  queue_target:'
  insertafter: "^config :pleroma, Pleroma.Repo,$"

pleroma_exiftool_version: "12.53"
pleroma_exiftool_name: "Image-ExifTool-{{ pleroma_exiftool_version }}"
pleroma_exiftool_url: "https://exiftool.org/Image-ExifTool-{{ pleroma_exiftool_version }}.tar.gz"

pleroma_interface_ipv4: "{{ uberspace_ip_private_v4 }}"

uberspace_domains_goal:
- "{{ pleroma_host }}"

inwx_records_a:
- "{{ uberspace_servicedomain }}"

pleroma_webbackends:
- path: "{{ pleroma_host }}"
  port: "{{ pleroma_port }}"

# password generation/encryption not yet working correctly, pre-set
#pleroma_secret: "{{ lookup('password', 'credentials/' + uberspace_loginname + '/' + 'pleroma_secret') }}"
