- name: Get deletion page
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.delete }}"
    headers: "{{ uberspace_headers }}"
    return_content: yes
  register: formresult

- name: Delete uberspace
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.deletequeue }}"
    headers: "{{ uberspace_headers }}"
    method: POST
    body_format: form-urlencoded
    body:
      _csrf_token: "{{ csrftoken }}"
    status_code: 302
  register: deleteresult
  changed_when: (deleteresult.location == uberspace_deleteresult_register_url) or (deleteresult.location == uberspace_deleteresult_login_url)

# - name: Show deletion result
#   debug:
#     var: deleteresult
