- name: Get authentication page
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.authentication }}"
    headers: "{{ uberspace_headers }}"
    return_content: yes
    follow_redirects: none
  register: formresult

- name: Deploy key
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.addkey }}"
    headers: "{{ uberspace_headers }}"
    method: POST
    body_format: form-urlencoded
    body:
      _csrf_token: "{{ csrftoken }}"
      ssh_key: "{{ uberspace_loginkey }}"
    status_code: 302
