- name: Get login form for CSRF token
  uri:
    url: "{{ uberspace_login_url }}"
    return_content: yes
  register: loginformresult

- name: Login to get session
  uri:
    url: "{{ uberspace_login_url }}"
    method: POST
    body_format: form-urlencoded
    body:
      _csrf_token: "{{ csrftoken }}"
      login: "{{ uberspace_loginname }}"
      password: "{{ uberspace_loginpassword }}"
      submit: "login"
    status_code: 302
  register: loginresult

- name: Store session as cookie
  set_fact:
    uberspace_cookie: "{{ loginresult.set_cookie.split(';')[0] }}"

- name: Get dashboard
  uri:
    url: "{{ uberspace_dashboard_url }}"
    headers: "{{ uberspace_headers }}"
    return_content: yes
  register: dashboardresult

- name: Show dashboardresult page
  debug:
    var: dashboardresult
