- name: Check loginname availability
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.register }}"
  register: checkresult
  failed_when: checkresult.status!=200 and checkresult.status!=403
- name: Do registration
  when: uberspace_action_setup and checkresult.status==200 and checkresult.msg == "OK (2 bytes)"
  include_tasks: register.yml
- name: Lookup session
  vars:
    uberspace_session:  "{{ lookup('file', uberspace_sessionfile, errors='ignore') }}"
  when: uberspace_session | default('', true) | trim != ''
  set_fact:
    uberspace_cookie: "uberspace_session={{ uberspace_session }}"
- name:
  block:
  - name: Get main dashboard page to check if session expired
    delegate_to: localhost
    uri:
      url: "{{ uberspace_url_dashboard }}"
      headers: "{{ uberspace_headers }}"
      return_content: yes
      follow_redirects: none
    register: dashboardresult
  rescue:
  - name: Re-login
    when: checkresult.status==403
    include_tasks: login.yml
- name: Do login
  when: checkresult.status==403 and uberspace_cookie is not defined
  include_tasks: login.yml
- name: Do passwordset
  when: uberspace_action_setup
  include_tasks: password.yml
- name: Do key deployment
  when: uberspace_action_setup
  import_tasks: key.yml
- name: Do facts gathering
  tags: gatherfacts
  when: not uberspace_action_setup and not uberspace_action_delete
  import_tasks: gather_facts.yml
- name: Do delete
  when: uberspace_action_delete
  include_tasks: delete.yml
