- name: Check loginname availability
  uri:
    url: "{{ uberspace_register_url }}"
  register: checkresult
  failed_when: checkresult.status!=200 and checkresult.status!=403
- name: Do registration
  when: checkresult.status==200 and checkresult.msg == "OK (2 bytes)"
  include_tasks: register.yml
- name: Do login
  when: checkresult.status==403 and uberspace_session is not defined
  include_tasks: login.yml
- name: Do passwordset
  include_tasks: password.yml
- name: Do key deployment
  import_tasks: key.yml
# - name: Do delete
#   include_tasks: delete.yml
