- name: Get authentication page
  delegate_to: localhost
  uri:
    url: "{{ uberspace_authentication_url }}"
    headers: "{{ uberspace_headers }}"
    return_content: yes
  register: formresult

- name: Set password
  delegate_to: localhost
  uri:
    url: "{{ uberspace_setwebpassword_url }}"
    headers: "{{ uberspace_headers }}"
    method: POST
    body_format: form-urlencoded
    body:
      _csrf_token: "{{ csrftoken }}"
      password: "{{ uberspace_newloginpassword }}"
    status_code: 302
