- name: Get register form for CSRF token
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.registerform }}"
    return_content: yes
  register: formresult

- name: Store session as cookie
  set_fact:
    uberspace_cookie: "{{ formresult.set_cookie.split(';')[0] }}"

- name: Register
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.create }}"
    method: POST
    headers: "{{ uberspace_headers }}"
    body_format: form-urlencoded
    body:
      _csrf_token: "{{ csrftoken }}"
      mail: ""
      login: "{{ uberspace_loginname }}"
      u7: 1
    return_content: yes
    status_code: 302
  register: registerresult

- name: Store session as cookie
  set_fact:
    uberspace_cookie: "{{ registerresult.set_cookie.split(';')[0] }}"

- name: Output session cookie
  debug:
    msg: "{{ uberspace_cookie }}"

- name: Wait for space creation to finish
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.check }}"
    follow_redirects: none
    method: GET
    return_content: yes
    headers: "{{ uberspace_headers }}"
  register: checkresult
  until: checkresult.content == "active"
  retries: 100
  delay: 3 # Every 3 seconds
# - name: Output checkresult
#   debug:
#     var: checkresult

- name: Get firstboot page
  delegate_to: localhost
  uri:
    url: "{{ uberspace_urls.firstboot }}"
    method: GET
    return_content: yes
    headers: "{{ uberspace_headers }}"
  register: firstbootresult

# - name: Show firstboot page
#   debug:
#     var: firstbootresult
