- name: Reread supervisord config
  command:
    cmd: supervisorctl reread
  notify:
  - Update supervisord group prosody
  - Update supervisord group prosody_filer
- name: Update supervisord group prosody
  command:
    cmd: supervisorctl update prosody
  notify: Restart prosody
- name: Update supervisord group prosody_filer
  command:
    cmd: supervisorctl update prosody_filer
  notify: Restart prosody_filer
- name: Restart prosody
  command:
    cmd: supervisorctl restart prosody
- name: Restart prosody_filer
  command:
    cmd: supervisorctl restart prosody_filer
