- name: Deploy supervisord service description ini
  template:
    src: mosquitto.ini.j2
    dest: "{{ uberspace_services_dir }}/mosquitto.ini"
  notify: Restart mosquitto
- name: Activate supervisord daemon
  tags: supervisor
  supervisorctl:
    name: mosquitto
    state: present


- name: Create config directory
  tags: config
  file:
    state: directory
    path: "{{ mosquitto_configpath }}"
- name: Link default config
  tags: config
  file:
    state: link
    src: /etc/mosquitto/mosquitto.conf
    dest: "{{ mosquitto_configpath }}10_default.conf"
  notify: Restart mosquitto
- name: Deploy main config file
  tags: config
  template:
    src: mosquitto.conf.j2
    dest: "{{ uberspace_spacedir }}/etc/mosquitto/mosquitto.conf"
  notify: Restart mosquitto
- name: Deploy custom config file
  tags: config
  template:
    src: 20_custom.conf.j2
    dest: "{{ mosquitto_configpath }}20_custom.conf"
  notify: Restart mosquitto
- name: Deploy go-auth config file
  tags: authplugin,config
  template:
    src: 30_go-auth.conf.j2
    dest: "{{ mosquitto_configpath }}30_go-auth.conf"
  notify: Restart mosquitto

- name: Add mosquitto ports to the uberspace requested ones
  tags: ports
  set_fact:
    uberspace_ports_goal: "{{ uberspace_ports_goal | default([]) + mosquitto_ports }}"

- name: Add shared libraries to LD_LIBRARY_PATH, so shell commands work
  lineinfile:
    path: ~/.bash_profile
    line: 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/{{ uberspace_loginname }}/lib64/'
