- name: Download and extract MongoDB binaries
  tags: test
  file:
    path: "{{ mongodb_main_dir }}"
    state: directory
- name: Download and extract MongoDB binaries
  tags: test
  unarchive:
    src: "{{ mongodb_downloadurl }}"
    dest: "{{ mongodb_main_dir }}"
    remote_src: yes
    extra_opts:
    - --strip-components=1

- name: Deploy service
  template:
    src: mongodb.ini.j2
    dest: "{{ uberspace_services_dir }}/mongodb.ini"
  notify: Reread supervisord config

- name: install pymongo as a dependency for the following task
  pip:
    name: pymongo
    extra_args: --user

- name: Trigger update apt cache handler
  meta: flush_handlers

- mongodb_user:
    database: admin
    user: "{{ mongodb_admin_user }}"
    password: "{{ mongodb_admin_password }}"
    roles: root

# - name: setup mongodb
# #  tags: test
#   command: uberspace-setup-mongodb
#   args:
#     creates: "~/mongodb"
#   register: TEMPMDB
# - name: derive port and password
# #  tags: test
#   when: mongodb_port is not defined or mongodb_admin_password is not defined
#   set_fact:
#     mongodb_port: "{{ TEMPMDB.stdout | regex_search('Portnum#:(\\s[0-9]{5})')  }}"
#     mongodb_admin_password: "{{ TEMPMDB.stdout | regex_search('Password:(\\s.+)\\n')   }}"
# - name: output
# #  tags: test
#   debug:
#     msg: "mongodb_port: {{ mongodb_port.split(' ')[1] }} ; mongodb_admin_password: {{ mongodb_admin_password.split(' ')[1].split('\n')[0] }}"
# - name: derive mongo url
# #  tags: test
#   set_fact:
#     wekan_mongo_url: "mongodb://{{ wekan_mongo_user }}:{{ mongodb_admin_password }}@127.0.0.1:{{ mongodb_port }}/wekan?authSource=admin"
