- name: Create target dir
  file:
    path: "{{ mongodb_main_dir }}"
    state: directory
- name: Download and extract MongoDB binaries
  unarchive:
    src: "{{ mongodb_downloadurl }}"
    dest: "{{ mongodb_main_dir }}"
    remote_src: yes
    extra_opts:
    - --strip-components=1
  notify: Restart mongodb

- name: Find MongoDB binaries
  find:
    paths: "{{ mongodb_bin_dir }}"
  register: mongodb_binaries

- name: Link binaries into ~/bin
  loop: "{{ mongodb_binaries.files }}"
  file:
    state: link
    src: "{{ item.path }}"
    dest: "{{ uberspace_spacedir }}/bin/{{ item.path | basename }}"

- name: Deploy service
  template:
    src: mongodb.ini.j2
    dest: "{{ uberspace_services_dir }}/mongodb.ini"
  notify: Reread supervisord config

- name: install pymongo as a dependency for the following task
  pip:
    name: pymongo
    extra_args: --user

- name: Trigger update apt cache handler
  meta: flush_handlers

- mongodb_user:
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ mongodb_admin_password }}"
    database: admin
    user: "{{ mongodb_admin_user }}"
    password: "{{ mongodb_admin_password }}"
    update_password: on_create
    roles: root

- name: Deploy mongorc
  template:
    src: .mongorc.js.j2
    dest: "{{ uberspace_spacedir }}/.mongorc.js"
