uberspace_csrf_field: '<input type=\"hidden\" name=\"_csrf_token\" value=\"(.*)\" />'
uberspace_password_field: '<input type=\"password\" (.*) value=\"(.*)\" onkeyup=(.*) />'

uberspace_html_ipv4address: '<th>IPv4-Adresse</th>\s*<td>\s*<code>(.*)</code>'
uberspace_html_ipv6address: '<th>IPv6-Adresse</th>\s*<td>\s*<code>(.*)</code>'
uberspace_html_hostkeyfingerprint: "<th>{{ item.upper() }}</th>\\s*<td><code>(.*)</code>"
uberspace_html_hostname: '<th>Hostname</th>\s*<td>\s*<code>(.*)</code>'
uberspace_html_balance: '<h2><a name=\"balance\"></a>Dein Kontostand</h2>\s*<p>\s*&hellip; beträgt derzeit <strong>(.*)&nbsp;€</strong>'

uberspace_html_currentprice: '<input type=\"text\" name=\"price\" value=\"(.*)\" size=\"3\" style=\"text-align: center;\" id=\"accounting_price\" />'
uberspace_url_main: "https://dashboard.uberspace.de/"
uberspace_url_dashboard: "{{ uberspace_url_main }}dashboard/"

uberspace_domain_short_official: uber.space
uberspace_domain_official: "{{ uberspace_loginname }}.{{ uberspace_domain_short_official }}"
uberspace_mail: "{{ uberspace_loginname }}@{{ uberspace_domain_short_official }}"
uberspace_services_dir: "{{ uberspace_spacedir }}/etc/services.d"
uberspace_certificates_dir: "{{ uberspace_spacedir }}/etc/certificates"

uberspace_urls:
#  dashboard: "{{ uberspace_url_main }}dashboard/"
  registerform: "{{ uberspace_url_main }}register"
  register: "{{ uberspace_url_main }}register/check_name?login={{ uberspace_loginname }}&AjaxRequestUniqueId={{ lookup('pipe','date +%s%5N') }}"
  create: "{{ uberspace_url_main }}register/create"
  login: "{{ uberspace_url_main }}login"
  check: "{{ uberspace_url_dashboard }}ajax_state?AjaxRequestUniqueId={{ lookup('pipe','date +%s%5N') }}"
  firstboot: "{{ uberspace_url_dashboard }}firstboot"
  authentication: "{{ uberspace_url_dashboard }}authentication"
  setwebpassword: "{{ uberspace_url_dashboard }}set_web_password"
  addkey: "{{ uberspace_url_dashboard }}add_ssh_key"
  datasheet: "{{ uberspace_url_dashboard }}datasheet"
  delete: "{{ uberspace_url_dashboard }}delete"
  deletequeue: "{{ uberspace_url_dashboard }}delete_queue"
  deleteresult_register: "{{ uberspace_url_dashboard }}../register"
  deleteresult_login: "{{ uberspace_url_dashboard }}../login"
  accounting:  "{{ uberspace_url_dashboard }}accounting"

uberspace_headers:
  Cookie: "{{ uberspace_cookie }}"

csrftoken: "{{ formresult.content | regex_search(uberspace_csrf_field) | regex_replace(uberspace_csrf_field, '\\1')}}"
parsed_ipv4address: "{{ datasheetresult.content | regex_search(uberspace_html_ipv4address) | regex_replace(uberspace_html_ipv4address, '\\1')}}"
parsed_ipv6address: "{{ datasheetresult.content | regex_search(uberspace_html_ipv6address) | regex_replace(uberspace_html_ipv6address, '\\1')}}"
parsed_hostname: "{{ datasheetresult.content | regex_search(uberspace_html_hostname) | regex_replace(uberspace_html_hostname, '\\1')}}"
parsed_hostkeyfingerprint: "{{ datasheetresult.content | regex_search(uberspace_html_hostkeyfingerprint) | regex_replace(uberspace_html_hostkeyfingerprint, '\\1')}}"
parsed_balance: "{{ accountingresult.content | regex_search(uberspace_html_balance) | regex_replace(uberspace_html_balance, '\\1')}}"
parsed_currentprice: "{{ accountingresult.content | regex_search(uberspace_html_currentprice) | regex_replace(uberspace_html_currentprice, '\\1')}}"
