geogames:
- event:
    name: Event
    logo: logo.png
    handle: event
    webpath: "event"
  groups_mobile:
  - name: Faction 1
    faction: factionone
    groups:
    - tid: g1
      name: Group 1
  - name: Faction 2
    faction: factiontwo
    groups:
    - tid: g2
      name: Group 2
  groups_stationary:
  - name: Stationen
    faction: factionstations
    groups:
    - tid: s1
      name: Station 1
  groups_special:
  - name: Sonderrollen
    faction: specialfaction
    groups:
    - tid: XX
      name: Game-Master