- name: Prepare Mongodb
#  tags: wekan
  vars:
    mongodb_application_db: "{{ wekan_db_user }}"
    mongodb_application_user: "{{ wekan_db_user }}"
    mongodb_application_password: "{{ wekan_db_pw }}"
  include_role:
    name: uberspace_mongodb
    apply:
      tags: wekan

- name: "Select Node version {{ node_version }}"
  command: "uberspace tools version use node {{ node_version }}"

- name: Create target folder
  tags: wekan
  file:
    path: "{{ wekan_main_dir }}"
    state: directory

- name: "Download from {{ wekan_download_url }} to {{ wekan_main_dir }}"
  tags: wekan
  get_url:
    url: "{{ wekan_download_url }}"
    dest: "{{ wekan_main_dir }}"

- name: "Extract to {{ wekan_main_dir }}"
  # Direct URL extract runs infinitively
#  tags: wekan
  unarchive:
    remote_src: true
    unsafe_writes: true
    src: "{{ wekan_main_dir }}/{{ wekan_download_url | urlsplit('path') | basename }}"
    dest: "{{ wekan_main_dir }}"

- name: Delete two files
  tags: wekan
  loop:
  - node-gyp
  - node-pre-gyp
  file:
    path: "{{ wekan_main_dir }}/bundle/programs/server/node_modules/.bin/{{ item }}"
    state: absent

- name: Install wekan
  tags: wekan
  loop:
  - node-gyp
  - node-pre-gyp
  - fibers
  npm:
    path: "{{ wekan_main_dir }}/bundle/programs/server"

# - name: install
#   template:
#     src: templates/wekan-setup.j2
#     dest: ~/wekan-setup
#     mode: "u+x"



# Problems:
#* wget https://releases.wekan.team/wekan-4.22.zip
#     https://github.com/wekan/wekan/archive/v4.22.zip
#* unzip v4.22.zip
#* cd bundle/programs/server
#* npm install
#  => npm ERR! bcrypt@3.0.8 install: `node-pre-gyp install --fallback-to-build`

# https://install.meteor.com

# in `/home/foobar/projekte/wekan/bundle/programs/server` - `npm_install`
