- name: Set PostgreSQL version
  debug:
    msg: "Set desired PostgreSQL version as uberspace_tools_goal.postgresql via uberspace_account role"
- name: Run tools tasks of uberspace account role
  tags: tools
  import_role:
    name: uberspace_account
    tasks_from: tools

- name: Configure environment (bash_profile)
  # lineinfile:
  #   path: ~/.bash_profile
  #   line:
  #   insertbefore: export PATH
  blockinfile:
    path: ~/.bash_profile
    block: "{{ lookup('template', 'bash_profile.j2') }}"
    insertbefore: export PATH
- name: Configure environment (bashrc)
  # lineinfile:
  #   path: ~/.bash_profile
  #   line:
  #   insertbefore: export PATH
  blockinfile:
    path: ~/.bashrc
    block: "{{ lookup('template', 'bashrc.j2') }}"

- name: Create .pgpass file
  template:
    src: pgpass.j2
    dest: "{{ uberspace_spacedir }}/.pgpass"
    mode: "0600"
- name: Store password into temp file
  lineinfile:
    line: "{{ postgres_password }}"
    path: "{{ uberspace_spacedir }}/.pgpass.tmp"
    create: true
- name: Initialize PostgreSQL cluster
  environment:
    PGPASSFILE: "{{ uberspace_spacedir }}/.pgpass"
  shell: 'initdb --pwfile="{{ uberspace_spacedir }}/.pgpass.tmp" --auth=scram-sha-256 -E UTF8 -D {{ postgres_main_dir }}/data/'
  args:
    creates: "{{ postgres_main_dir }}/data/"
- name: remove temp password file
  file:
    dest: "{{ uberspace_spacedir }}/.pgpass.tmp"
    state: absent

- name: Change config file to set socket directory
  lineinfile:
    dest: "{{ postgres_main_dir }}/data/postgresql.conf"
    regexp: 'unix_socket_directories'
    line: "unix_socket_directories = '{{ uberspace_spacedir }}/tmp'"


# - name: Create postgres file path
#   loop:
#   - "{{ postgres_main_dir }}"
#   - "{{ postgres_configfile | dirname }}"
#   - "{{ postgres_pidfile | dirname }}"
#   file:
#     state: directory
#     path: "{{ item }}"
