uberspace_loginname: "{{ ansible_user }}"

uberspace_credentialstore_location: "credentials/"
uberspace_credential_destination: "{{ uberspace_credentialstore_location }}uberspace/{{ uberspace_loginname }}/"
uberspace_sessionfile: "{{ uberspace_credential_destination }}session"
uberspace_passwordfetch_destination: "{{ uberspace_credential_destination }}loginpassword"
uberspace_newloginpassword: "{{ lookup('password', uberspace_passwordfetch_destination) }}"
uberspace_loginpassword: "{{ lookup('file', uberspace_passwordfetch_destination) }}"
uberspace_loginkey_path: "~/.ssh/id_uberspace_{{ uberspace_loginname }}"
uberspace_loginkey: "{{ lookup('file', uberspace_loginkey_path + '.pub', errors='ignore') }}"
uberspace_mycnffetch_destination: "{{ uberspace_credential_destination }}mycnf"
uberspace_action_delete: false
uberspace_action_setup: false

uberspace_session: "{{ lookup('file', uberspace_sessionfile, errors='ignore') }}"

uberspace_spacedir: "{{ '/home/' + uberspace_loginname }}"
uberspace_webroot: "{{ '/var/www/virtual/' + uberspace_loginname + '/html'}}"

inwx_pw: "{{ lookup('file', uberspace_credentialstore_location + 'inwx/' + inwx_user + '-pw') }}"
inwx_ttl: 3600
inwx_records_srv: {}
inwx_records_srv_protocol: "tcp"

uberspace_shellaliases_block: |
  alias s="screen -rxU || screen"
  alias l='ls -lah'
