uberspace_loginname: "{{ ansible_user }}"

uberspace_sessionfile: "credentials/uberspace_session_{{ uberspace_loginname }}"
uberspace_passwordfetch_destination: "credentials/uberspace_loginpassword_{{ uberspace_loginname }}"
uberspace_newloginpassword: "{{ lookup('password', uberspace_passwordfetch_destination) }}"
uberspace_loginpassword: "{{ lookup('file', uberspace_passwordfetch_destination) }}"
uberspace_loginkey_path: "~/.ssh/id_uberspace_{{ uberspace_loginname }}"
uberspace_loginkey: "{{ lookup('file', uberspace_loginkey_path + '.pub', errors='ignore') }}"
uberspace_mycnffetch_destination: "credentials/uberspace_mycnf_{{ uberspace_loginname }}"
uberspace_action_delete: false
uberspace_action_setup: false

uberspace_session: "{{ lookup('file', uberspace_sessionfile, errors='ignore') }}"

uberspace_spacedir: "{{ '/home/' + uberspace_loginname }}"
uberspace_domain_official: "{{ uberspace_loginname }}.{{ uberspace_domain_short_official }}"
uberspace_mail: "{{ uberspace_loginname }}@{{ uberspace_domain_short_official }}"
uberspace_services_dir: "{{ uberspace_spacedir }}/etc/services.d"
uberspace_certificates_dir: "{{ uberspace_spacedir }}/etc/certificates"

inwx_pw: "{{ lookup('file', 'credentials/' + 'inwx-' + inwx_user + '-pw') }}"
inwx_ttl: 3600
inwx_records_srv_protocol: "tcp"
