- name: Reread supervisord config
  command:
    cmd: supervisorctl reread
  notify: Update supervisord group mongodb
- name: Update supervisord group mongodb
  command:
    cmd: supervisorctl update mongodb
  notify: Restart mongodb
- name: Restart mongodb
  command:
    cmd: supervisorctl restart mongodb
