- name: Reread supervisord config
  command:
    cmd: supervisorctl reread
  notify:
  - Update supervisord mongodb groups
- name: Update supervisord mongodb groups
  command:
    cmd: supervisorctl update mongodb
  notify: Restart mongodb
- name: Restart mongodb
  command:
    cmd: supervisorctl restart mongodb
