prosody_downloadurl: https://prosody.im/downloads/source/prosody-0.11.5.tar.gz
prosody_filer_downloadurl: github.com/ThomasLeister/prosody-filer
prosody_version: "{{ prosody_downloadurl | basename | splitext | first | splitext | first }}"
prosody_configfile_name: "prosody.cfg.lua"
prosody_configfile: "{{ prosody_install_dir }}/etc/prosody/{{ prosody_configfile_name }}"
prosody_pidfile: "{{ prosody_main_dir }}/prosody.pid"

prosody_dhparam_size: 2048
prosody_curversion_dir: "{{ prosody_main_dir }}/{{ prosody_version }}"
#prosody_upload_dir: "{{ prosody_install_dir }}/var/lib/prosody/http_upload"
prosody_upload_dir: "{{ prosody_main_dir }}/data/http_upload"
prosody_communityplugins_dir: "{{ prosody_install_dir }}/var/lib/prosody/community-plugins"
prosody_dhparam_path: "{{ prosody_main_dir }}/ssl/{{ prosody_host }}.prosody.dhparams.pem"
prosody_filer_dir: "{{ uberspace_spacedir }}/go/src/{{ prosody_filer_downloadurl }}"

prosody_host: "{{ uberspace_servicedomain }}.{{ uberspace_basedomain }}"

prosody_domain_muc: conference
prosody_domain_proxy: proxy
#prosody_domain_upload: upload
prosody_servicedomain_muc: "{{ prosody_domain_muc }}{{ (prosody_domain_muc != '') | ternary('.','') }}{{ uberspace_servicedomain }}"
prosody_servicedomain_proxy: "{{ prosody_domain_proxy }}{{ (prosody_domain_proxy != '') | ternary('.','') }}{{ uberspace_servicedomain }}"
#prosody_servicedomain_upload: "{{ prosody_domain_upload }}{{ (prosody_domain_upload != '') | ternary('.','') }}{{ uberspace_servicedomain }}"
prosody_fulldomain_muc: "{{ prosody_domain_muc }}.{{ prosody_host }}"
prosody_fulldomain_proxy: "{{ prosody_domain_proxy }}.{{ prosody_host }}"
# prosody_fulldomain_upload: "{{ prosody_domain_upload }}.{{ prosody_host }}"
prosody_fulldomain_upload: ""

prosody_install_dir: "{{ uberspace_spacedir }}"
prosody_certificates_dir: "{{ uberspace_certificates_dir }}"
prosody_adminaccount: ""
prosody_admins: ["{{ prosody_adminaccount }}@{{ prosody_host }}"]
prosody_users: []
prosody_users_complete: "{{ prosody_admins + prosody_users }}"
prosody_adminmail: "{{ uberspace_mail }}"
prosody_secret: "{{ lookup('password', 'credentials/' + 'prosody_secret') }}"
prosody_upload_secret: "{{ lookup('password', 'credentials/' + 'prosody_upload_secret') }}"
# prosody_db_user: prosody
# prosody_db_pw: "{{ lookup('password', 'credentials/' + 'prosody_dbuser_pw') }}"
# prosody_db_name: prosody_dev
# prosody_db_host: localhost

prosody_interface_ipv4: "{{ uberspace_ip_private_v4 }}"
prosody_interface_ipv6: "{{ uberspace_ip_private_v6 }}"

uberspace_domains_goal:
- "{{ prosody_host }}"
- "{{ prosody_fulldomain_muc }}"
- "{{ prosody_fulldomain_proxy }}"
# - "{{ prosody_fulldomain_upload }}"
prosody_ports:
# - "{{ prosody_port_http }}"
# - "{{ prosody_port_https }}"
- "{{ prosody_port_client }}"
- "{{ prosody_port_client_tls }}"
- "{{ prosody_port_server }}"
# - "{{ prosody_port_proxy65 }}"
# - "{{ prosody_port_upload }}"
# - "{{ prosody_port_transfer }}"
#uberspace_ports_goal: "{{ uberspace_ports_goal | default([]) + prosody_ports }}"
inwx_records_a:
- "{{ uberspace_servicedomain }}"
- "{{ prosody_servicedomain_muc }}"
- "{{ prosody_servicedomain_proxy }}"
# - "{{ prosody_servicedomain_upload }}"
inwx_records_srv:
  xmpp-client:
    port: "{{ prosody_port_client }}"
    domains: ["{{ uberspace_servicedomain }}"]
  xmpps-client:
    port: "{{ prosody_port_client_tls }}"
    domains: ["{{ uberspace_servicedomain }}"]
  xmpp-server:
    port: "{{ prosody_port_server }}"
    domains: "{{ inwx_records_a }}"
prosody_webbackends:
- path: "/upload"
  port: 5050
- path: "/prosody"
  port: "{{ prosody_port_http }}"
- path: "/http-bind"
  port: "{{ prosody_port_http }}"
# - path: "/.well-known/host-meta"
#   port: "{{ prosody_port_http }}"
# - path: "/.well-known/host-meta.json"
#   port: "{{ prosody_port_http }}"
